### ISSUE TITLE
Accessing the same ATLAS data from both C++ and Fortran

### ISSUE THREAD

**Issue by benjaminmenetrier** [ecmwf/atlas#3]
Hello @wdeconinck. My problem is the following: I create an ATLAS structure (e.g. a `NodeColumns` object) in a C++ layer, and I would like to access it from a Fortran subroutine that is called by the C++ layer.

I have noticed that in Fortran, an `atlas_functionspace_NodeColumns` object can be initialized with a C pointer `type(c_ptr)`, which is probably the solution to my problem.

However, once I have generated the ATLAS structure in C++, I don't know what to pass to the Fortran interface, in order to access and modify the data  from the Fortran routine. Do you know how to do that?

Thank you.

**Comment by benjaminmenetrier** [comment]
OK,  I have found the solution for the ATLAS State that I am finally using:
 - in C++ : 
   + declare a State pointer:
   ```
   State * state = new State(...)
   ```
   + pass it to the Fortran function:
   ```
   my_fortran_subroutine_f90(state, ...)
   ```
 - in the C interface: pass the State pointer
  ```
  extern "C" {
    void my_fortran_subroutine_f90(State * state, ...);
  }
  ```
 - in Fortran: get the State pointer as a `type(c_ptr)` and use it to initialize a `type(atlas_state)`:
  ```
  subroutine my_fortran_subroutine_c(state_ptr,...) bind (c,name='my_fortran_function_f90')

  type(c_ptr),intent(in),value :: state_ptr
  type(atlas_state) :: state

  state = atlas_state(state_ptr)

  end subroutine my_fortran_subroutine_c
  ```

Maybe it would be worth adding an example in the documentation. Not a top priority though...

**Comment by wdeconinck** [comment]
Hi @benjaminmenetrier  I'm happy you figured it out.
Perhaps I could advise to you to use atlas_FieldSet instead of atlas_State?
The ```State``` is more of an experimental tryout I once did to show Yannick Tremolet what is possible.
Conceptually it is the same as a ```FieldSet``` with the difference that it could be constructed from a configuration as shown experimentally here:
https://github.com/ecmwf/atlas/blob/0.19.0/src/tests/grid/test_state.cc#L137
If you don't need that, then you could probably use ```FieldSet``` instead, as that is more widespread used in API's, and maintained.

**Comment by benjaminmenetrier** [comment]
Thank you for the tip! I'll switch to FieldSet now, before the use of State is too widespread in the code...
