### ISSUE TITLE
Supporting a stretched rotated limited area grid.

### ISSUE THREAD

**Issue by MarekWlasak** [ecmwf/atlas#53]
From my reading of the code  the current capability allows  xy space to have a varied delta_x in the x direction, but a fixed delta_y  in the y direction, when using StructuredGrid data structure. 

The MetOffice is regional ukv model is a rotated grid with is separable in the x and y directions but has varied delta_x in the x direction and varied delta y in the y direction (It has a constant delta_x and delta_y in an internal region of 1.5 km and then stretches to 4 km in a border region. )

There are three possilble implementations - @wdeconinck - it would be great to get your thoughts on this.
All involve creating an additional example grid.

Version A:
1) Have the xy object to have a regular grid with constant delta_x and delta_y to that of the interior part. 
2) Create a projection (say stretched_rotated_lonlat")  that involves a stretch in the x or y directions (followed by a "unrotate" ... to get to the real longitude and latitudes of the grid. The stretch itself would be defined by reading a vector for both x and y from the yaml file.

Version B:
1) As Version A but use the stretched capability in xy in the x direction. 
2) The projection would then stretch in the y direction and then rotate.

Version C :
1) As Version A, but implement a separate stretched projection for both dimensions.
2) Then add the capability to define projections as a product of a simpler projections.

**Comment by wdeconinck** [comment]
Hi @MarekWlasak , Am I right to assume that the x and y coordinates are completely orthogonal, in the sense that all the resulting mesh is made out of straight lines (in `{x,y}` coordinates, of course `{lon,lat}` will be rotated etc) ?
The `StructuredGrid` as it is now is made out of 2 orthogonal "Spacings" : `XSpace` and `YSpace`, which I think you got reversed in your question.
Whereas there's only one YSpace, which can be any single Spacing (e.g. an array of custom y-coordinates like `CustomSpacing`), the `XSpace` itself is in fact an array of `LinearSpacing`, allowing a different `LinearSpacing` for each parallel (`y`).

- There is indeed the possibility to just define the grid as a `RegularGrid` (regional), which sets both `XSpace` and `YSpace` to a `LinearSpacing`, and then define a projection that stretches the extension zone only, and then applies rotation. Projections could be made up as desired ( e.g. combination of orthogonal stretchings, plus rotation, like you said).
I do not foresee any issue as long as the final projection is a continuous (C0) function (ideally C1 but not required) that can be inverted. Probably this is the easiest solution, without (or minimally) touching any existing code.
- Another possibility is to define a new grid type, which is hierarchically between `Grid` and `StructuredGrid`, which allows that `XSpace` be an array of `CustomSpacing` instead of `LinearSpacing`. In that case, the projection would only take care of rotation. As this would be a new grid type this is quite a bit more involved, and you cannot use `StructuredColumns` functionspace or `StructuredMeshGenerator` (without modifications). In the long term this would support more grids, and reduce the number of projections, and allow grids that cannot be handled by mapping a regulargrid.
- We can also think to support zones in the grid, like the extension zones. Not sure yet how that could best be achieved though. This becomes true CFD territory then.

**Comment by twsearle** [comment]
Just to say, the Atlantic Margin Model for the shelf seas is also on the UKV grid (I think!) So we would also be interested in this functionality.

**Comment by twsearle** [comment]
This will be fixed by PR #82

**Comment by wdeconinck** [comment]
The PR #82 has been merged, but some more refactoring with respect to the configuration of the "VariableResolutionProjection" is still expected in the near future
