### ISSUE TITLE
Allow atlas-run to use something other than srun

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/atlas#64]
Currently when I run the ATLAS ctests the script in tools/atlas-run uses srun when it is available.  However I would like to use mpiexec instead.  I cannot easily get rid of srun from the path as it is in /usr/bin.  Is it possible to enable the use of mpiexec in this situation?

**Comment by wdeconinck** [comment]
Hello @DJDavies2 , the use of atlas-run is optional, and is supposed to help running of tests of a single configuration both on login-nodes, compute-nodes, or post-processing nodes.
It may be that for your case you could disable the use: ```cmake -DENABLE_ATLAS_RUN=OFF ...```

If that doesn't work, you could try to edit the script so that it would work to set an environment variable like
```ATLAS_RUN_MPI_EXECUTABLE=mpiexec```

I'm happy to get this merged in.

**Comment by DJDavies2** [comment]
Thanks, -DENABLE_ATLAS_RUN=OFF has worked for me.
