### ISSUE TITLE
Stopping the interpolation of missing values during finite-element interpolation

### ISSUE THREAD

**Issue by twsearle** [ecmwf/atlas#78]
I believe I have set the metadata on my fields to reflect the missing values in my data (e.g `field.metadata().set("missing_value")` ). When I interpolate to a point on the edge of a missing-data region, I find that the missing values are weighted in the same away as non-missing values. This is a problem, as it mixes the missing_value into my data. Is it possible to stop this in atlas at the moment?

If not, I propose the conservative solution of setting the interpolated value to a missing value if any of the points used in the interpolation are missing data.

**Comment by wdeconinck** [comment]
There are a few ways that missing values can be interpreted, see https://github.com/ecmwf/atlas/blob/develop/src/tests/interpolation/test_interpolation_non_linear.cc
Perhaps @pmaciel can propose a solution?

**Comment by pmaciel** [comment]
Hi @twsearle, interpolation is interpreted as matrix multiplication: y = A x, for (x, y) the (input, output) values vectors, and A the interpolation weights matrix. So it is a linear operation, with the weights calculated geometricly (no dependance on the values).

In your case, you need to correct the weights to not touch missing values - that's a input data-dependant operation, and is therefore non-linear in this context, and is controlled by the 'non_linear' option. The unit test above shows two things:

1. setup the missing value, with 'missing_value' -- you already did that, but be aware you can also set a tolerance (for lossly-compressed data), or use NaN instead; and
2. setup the non-linear treatment, with 'non_linear'.

There are 3 options for non-linear treatment:
1. 'missing-if-any-missing': if an (output) point has contributions from (input) points where at least one is missing, the output is set to missing value;
2. 'missing-if-all-missing': ... from (input) points where all points are missing values, the output is set to missing value (the mv input point weights are set to 0, the others linearly rebalanced to sum(w)=1);
3. 'missing-if-heaviest-missing': if an (output) point has contributions from (input) points where some are missing, the output is set to missing value only if the most significant weight also corresponds to a missing value (the weight rebalancing is the same as above).

A sensible choice for 'non_linear' is 'missing-if-heaviest-missing', because it works well across large resolution changes in interpolations. The other options are also suitable depending on your situation, the choice would depend on your case.

Hope this helps!

**Comment by pmaciel** [comment]
Just for completeness and in any case, if you set any of the non-linear treatments, none of the points representing missing values are ever used for interpolation.

**Comment by twsearle** [comment]
@pmaciel Thanks! That is really helpful I will give this a try today. Would it be OK to copy and paste your answer into the documentation somewhere? I am happy to have a go at a pull request to update the docs if you like.

**Comment by wdeconinck** [comment]
Hi @twsearle you are more than welcome to add documentation.
The documentation repo is here https://github.com/ecmwf/atlas-docs
I need to play with Github Actions there still to automate the deployment and hosting when changes are made.
For now I manually recreate / upload the docs

**Comment by pmaciel** [comment]
@twsearle do let us know if any of the methods above works for you. Also, feel free to suggest other methods that might be more suitable :-)

**Comment by twsearle** [comment]
Thanks that seems to work as expected and solves my problem!
